# Generated by Django 4.0.4 on 2026-05-13 19:37

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20250704_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local_name',
            field=models.CharField(blank=True, default='', help_text='Nepali or other local-language name (e.g. Badam, Kaju).', max_length=200, verbose_name='Local name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.category_image_path),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='products_category_unique_root_name'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'name'), name='products_category_unique_child_name'),
        ),
    ]
